### ISSUE TITLE
[QUESTION] bypass branch protections

### ISSUE THREAD

**Issue by aleboulanger** [desbo/merge-pr-action#12]
does the action will bypass branch protections ? 
I mean if other requirement are need to merge the branch, does the action will bypass them ?

**Comment by aleboulanger** [comment]
I found that you are not using the --auto option for the merge of the PR. 
is it something that you could add ? 
`gh pr merge "${PR_URL}" --squash --auto`  instead of `gh pr merge "${PR_URL}" --squash` for `MERGE_METHOD=squash`

**Comment by desbo** [comment]
@aleboulanger it’s been a while since I worked with this action, but I’m pretty confident it won’t bypass branch protection. I would recommend verifying this on a test repo though.

The `—auto` flag wasn’t something I needed when I created this action but I’d welcome a PR to add it (ideally behind a Workflow setting) if it’d be useful to you.
